### ISSUE TITLE
Meson error during configure when trying to enable tests

### ISSUE THREAD

**Issue by tgurr** [MusicPlayerDaemon/libmpdclient#8]
```
~/Downloads/libmpdclient-2.13 $ meson -Dtest=true . output
The Meson build system
Version: 0.41.1
Source dir: /home/HEILBRONN/hn11022/Downloads/libmpdclient-2.13
Build dir: /home/HEILBRONN/hn11022/Downloads/libmpdclient-2.13/output
Build type: native build
Project name: libmpdclient
Native c compiler: cc (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "getaddrinfo": YES
Configuring config.h using configuration
Configuring version.h using configuration
Compiler for c supports argument -Wall: YES
Compiler for c supports argument -Wextra: YES
Compiler for c supports argument -Wno-deprecated-declarations: YES
Compiler for c supports argument -Wmissing-prototypes: YES
Compiler for c supports argument -Wshadow: YES
Compiler for c supports argument -Wpointer-arith: YES
Compiler for c supports argument -Wstrict-prototypes: YES
Compiler for c supports argument -Wcast-qual: YES
Compiler for c supports argument -Wwrite-strings: YES
Compiler for c supports argument -Wl,--version-script=/home/HEILBRONN/hn11022/Downloads/libmpdclient-2.13/libmpdclient.ld: YES
Found pkg-config: /usr/host/bin/pkg-config (0.29.2)
Native dependency check found: YES 0.11.0
Build targets in project: 5
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 307, in run
    app.generate()
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 182, in generate
    g.generate(intr)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 194, in generate
    self.generate_target(t, outfile)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 445, in generate_target
    elem = self.generate_link(target, outfile, outname, obj_list, linker, pch_objects)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/mesonbuild/backend/ninjabackend.py", line 2331, in generate_link
    target.install_rpath)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/mesonbuild/compilers.py", line 839, in build_rpath_args
    return self.build_unix_rpath_args(build_dir, from_dir, rpath_paths, install_rpath)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/site-packages/mesonbuild/compilers.py", line 768, in build_unix_rpath_args
    relative = os.path.relpath(p, from_dir)
  File "/usr/x86_64-pc-linux-gnu/lib/python3.6/posixpath.py", line 448, in relpath
    raise ValueError("no path specified")
ValueError: no path specified
```

Without the tests it works fine:

```
~/Downloads/libmpdclient-2.13 $ meson -Dtest=false . output
The Meson build system
Version: 0.41.1
Source dir: /home/HEILBRONN/hn11022/Downloads/libmpdclient-2.13
Build dir: /home/HEILBRONN/hn11022/Downloads/libmpdclient-2.13/output
Build type: native build
Project name: libmpdclient
Native c compiler: cc (gcc 6.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "getaddrinfo": YES
Configuring config.h using configuration
Configuring version.h using configuration
Compiler for c supports argument -Wall: YES
Compiler for c supports argument -Wextra: YES
Compiler for c supports argument -Wno-deprecated-declarations: YES
Compiler for c supports argument -Wmissing-prototypes: YES
Compiler for c supports argument -Wshadow: YES
Compiler for c supports argument -Wpointer-arith: YES
Compiler for c supports argument -Wstrict-prototypes: YES
Compiler for c supports argument -Wcast-qual: YES
Compiler for c supports argument -Wwrite-strings: YES
Compiler for c supports argument -Wl,--version-script=/home/HEILBRONN/hn11022/Downloads/libmpdclient-2.13/libmpdclient.ld: YES
Build targets in project: 2
```

**Comment by MaxKellermann** [comment]
This is a Meson crash, and clearly a Meson bug. This must not happen.
It may be caused by a bug in our `meson.build`, but such a bug should result in a Meson error message. As long as we don't have such an error message, the existence of such a bug is speculation. There is little I can do for you, until Meson fixes the bug.
